### ISSUE TITLE
TypeError: Invalid shape in AE.ipynb

### ISSUE THREAD

**Issue by rabiaedayilmaz** [sarperyn/introduction-to-autoencoders#1]
In `def visualize_results(model,data_loader,data):` function, the line `ax.imshow((np.transpose(img,(1, 2, 0))*255).astype(np.uint8),cmap='gray')` causes an error. The error message is `TypeError: Invalid shape (28, 28, 1) for image data
`. Commenting and replacing that line with `ax.imshow(np.squeeze(img), cmap='gray')` solved this problem.

**Comment by sarperyn** [comment]
Those functions are not generalized. They only serve my purposes. I will generalize them as soon as possible.
